### ISSUE TITLE
typo in 50_mapping.Rmd

### ISSUE THREAD

**Issue by ymgan** [SCAR/EGABIcourse19#8]
chunk somap2c should be:

```{r somap2c}
mymap$ice$plotargs$col[[1]] <- "green"
```

**Comment by raymondben** [comment]
Thanks for picking that up. I'd have to go back and check the code, but I am pretty sure this is a difference between SOmap versions - the code in `50_mapping.Rmd` needs the development version of SOmap (see the note in that Rmd - install with `remotes::install_github("AustralianAntarcticDivision/SOmap", ref = "dev-0.5")`). Unfortunately we didn't get time to merge the development version of SOmap into master before this course, which would have avoided this confusion.
I will leave the issue open until I check the code.

**Comment by raymondben** [comment]
Yup - it's a version difference. With the current master branch of SOmap (version 0.4.0) it needs `mymap$ice$...`, but with dev (which will be version 0.5.x when it is merged to master) it's `mymap$ice[[1]]$...`.
The reason for this is that in the dev version, all plottable elements of an SOmap object are now always lists, because there can be multiple parts to an element (those parts form the list, even if it's a list of only one thing when there's only one thing to plot).
Welcome to the bleeding edge of "we are making this code up as we go along"!! Sorry for the confusion.

**Comment by ymgan** [comment]
Great!! Thanks for clarifying!!
